server:
  port: 9991

axoniq:
  axonhub:
    servers: localhost:8124,localhost:8125,localhost:8126
    command-threads: 4
    query-threads: 4
    token: this-is-token-for-demo2

logging:
  level:
    io.grpc.netty.NettyServerTransport: WARN
    io.axoniq: INFO

axon:
  eventhandling:
    processors:
      sample:
        mode: tracking
        batch-size: 500
        initial-segment-count: 4
        thread-count: 4


  serializer:
    general: jackson
    messages: jackson

management:
  endpoint:
    health:
      show-details: always
spring:
  application:
    name: AxonHubClient
