create table task
(
    id                  BIGINT not null generated by default as identity,
    task_id             varchar(200),
    data                blob,
    type                varchar(200),
    status              INTEGER,
    status_on_error     INTEGER,
    reschedule_interval BIGINT,
    task_executor       varchar(200),
    timestamp           BIGINT not null
);
