UPDATE PATH_MAPPING t SET t.PATH = 'PATCH:/v1/**' WHERE t.PATH LIKE 'PATCH:/v1/*' ;
UPDATE PATH_MAPPING t SET t.PATH = 'DELETE:/v1/**' WHERE t.PATH LIKE 'DELETE:/v1/*' ;
UPDATE PATH_MAPPING t SET t.PATH = 'POST:/v1/**' WHERE t.PATH LIKE 'POST:/v1/*' ;
UPDATE PATH_MAPPING t SET t.PATH = 'GET:/v1/**' WHERE t.PATH LIKE 'GET:/v1/*' ;