create table RAFT_PROCESSOR_LOAD_BALANCING
(
    CONTEXT  VARCHAR(255) not null,
    NAME     VARCHAR(255) not null,
    STRATEGY VARCHAR(255) not null,
    primary key (CONTEXT, NAME)
);

insert into RAFT_PROCESSOR_LOAD_BALANCING (CONTEXT, NAME, STRATEGY)
select CONTEXT, NAME, STRATEGY
from PROCESSOR_LOAD_BALANCING;
