insert into path_mapping (path, role) values ('GET:/v1/backup/filenames', 'ADMIN');
insert into path_mapping (path, role) values ('POST:/v1/events', 'WRITE');
insert into path_mapping (path, role) values ('POST:/v1/snapshots', 'WRITE');
insert into path_mapping (path, role) values ('POST:/v1/queries/run', 'WRITE');
insert into path_mapping (path, role) values ('POST:/v1/commands/run', 'WRITE');
insert into path_mapping (path, role) values ('DELETE:/v1/*', 'ADMIN');
insert into path_mapping (path, role) values ('PATCH:/v1/*', 'ADMIN');
insert into path_mapping (path, role) values ('POST:/v1/*', 'ADMIN');
insert into path_mapping (path, role) values ('GET:/v1/*', 'READ');
