create table jpa_raft_group_application (
  id  BIGINT generated by default as identity,
  group_id varchar(255) not null,
  hashed_token varchar(255) not null,
  name varchar(255) not null,
  token_prefix varchar(255) not null
);

create table jpa_raft_group_application_roles (
  jpa_raft_group_application_id BIGINT references jpa_raft_group_application(id),
  roles varchar(255) not null,
  primary key (jpa_raft_group_application_id,roles)
);

