create table jpa_context_user
(
    id       BIGINT generated by default as identity,
    context  varchar(255) not null,
    username varchar(255) not null,
    password varchar(255)
);

create table jpa_context_user_roles
(
    jpa_context_user_id BIGINT references jpa_context_user (id),
    roles               varchar(255) not null,
    primary key (jpa_context_user_id, roles)
);
