create table extension_package
(
    id        bigint generated by default as identity primary key,
    extension varchar(200) not null,
    version   varchar(200) not null,
    filename  varchar(200) not null,
);


create table extension
(
    id                   bigint generated by default as identity primary key,
    extension_package_id bigint       not null references extension_package (id),
    context              varchar(200) not null,
    configuration        clob,
    active               boolean
);

create table admin_extension
(
    id                   bigint generated by default as identity primary key,
    extension_package_id bigint       not null references extension_package (id),
    context              varchar(200) not null,
    configuration        clob,
    active               boolean
);


insert into PATHS_TO_FUNCTIONS
values ('GET:/v1/extensions', 'GET_EXTENSIONS');

insert into PATHS_TO_FUNCTIONS
values ('GET:/v1/extensions/configuration', 'GET_EXTENSION_CONFIGURATION');

insert into PATHS_TO_FUNCTIONS
values ('DELETE:/v1/extensions', 'DELETE_EXTENSION');

insert into PATHS_TO_FUNCTIONS
values ('POST:/v1/extensions', 'ADD_EXTENSION');

insert into PATHS_TO_FUNCTIONS
values ('DELETE:/v1/extensions/context', 'UNREGISTER_EXTENSION');

insert into PATHS_TO_FUNCTIONS
values ('POST:/v1/extensions/status', 'ACTIVATE_EXTENSION');

insert into PATHS_TO_FUNCTIONS
values ('POST:/v1/extensions/configuration', 'CONFIGURE_EXTENSION');

insert into FUNCTION_ROLES(function, role)
values ('GET_EXTENSIONS', 'ADMIN');

insert into FUNCTION_ROLES(function, role)
values ('GET_EXTENSION_CONFIGURATION', 'ADMIN');

insert into FUNCTION_ROLES(function, role)
values ('DELETE_EXTENSION', 'ADMIN');

insert into FUNCTION_ROLES(function, role)
values ('ADD_EXTENSION', 'ADMIN');

insert into FUNCTION_ROLES(function, role)
values ('UNREGISTER_EXTENSION', 'ADMIN');

insert into FUNCTION_ROLES(function, role)
values ('ACTIVATE_EXTENSION', 'ADMIN');

insert into FUNCTION_ROLES(function, role)
values ('CONFIGURE_EXTENSION', 'ADMIN');