create table extension
(
    id            bigint generated by default as identity primary key,
    context       varchar(200) not null,
    extension     varchar(200) not null,
    version       varchar(200) not null,
    filename      varchar(200) not null,
    configuration clob,
    active        boolean
);

create table admin_extension
(
    id            bigint generated by default as identity primary key,
    context       varchar(200) not null,
    extension     varchar(200) not null,
    version       varchar(200) not null,
    filename      varchar(200) not null,
    configuration clob,
    active        boolean
);

