apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: sample
  labels:
    app: sample
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
        - name: sample
          image: seu.gcr.io/axoniq-devops/sample-command-processor-axonserver-client:4.3-SNAPSHOT
          imagePullPolicy: Never
          ports:
            - containerPort: 9900
              protocol: TCP
              name: http
          env:
            - name: AXON_AXONSERVER_SERVERS
              value: axonserver-enterprise.default.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: sample-gui
  labels:
    app: sample
spec:
  sessionAffinity: ClientIP
  selector:
    app: sample
  clusterIP: None
