version: '3.7'

services:
  sample-command-processor-axonserver-client:
    image: sample-command-processor-axonserver-client
    environment:
      - SPRING_PROFILES_ACTIVE=events,commands,queries
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/sample
      - SPRING_DATASOURCE_USERNAME=demouser
      - SPRING_DATASOURCE_PASSWORD=thepassword
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - AXON.AXONSERVER.SERVERS=axonserver-enterprise-1
    ports:
      - 9900:9900
    deploy:
      replicas: 2
  postgres-db:
    image: postgres
    environment:
      - POSTGRES_DB=axon-scale-demo
      - POSTGRES_USER=demouser
      - POSTGRES_PASSWORD=thepassword
    volumes:
      - postgres-datadir:/var/lib/postgresql/data
    deploy:
      replicas: 1
volumes:
  postgres-datadir:
