version: '3.3'

services:
  axonserver-enterprise-1:
    image: axonserver-enterprise
    hostname: axonserver-enterprise-1
    environment:
      - AXONIQ_AXONSERVER_EVENT_STORAGE=/eventstorage
      - AXONIQ_AXONSERVER_SNAPSHOT_STORAGE=/eventstorage
      - AXONIQ_AXONSERVER_CONTROLDB-PATH=/controldb
      - AXONIQ_AXONSERVER_NAME=axonserver-enterprise-1
      - AXONIQ_AXONSERVER_HOSTNAME=axonserver-enterprise-1
      - AXONIQ_AXONSERVER_REPLICATION_FLOW-BUFFER=50
      - AXONIQ_AXONSERVER_REPLICATION_MAX-SNAPSHOT-CHUNKS-PER-BATCH=10
      - AXONIQ_AXONSERVER_REPLICATION_MAX-ENTRIES-PER-BATCH=10
      - AXONIQ_AXONSERVER_REPLICATION_LOG-STORAGE-FOLDER=/raft-log
      - SPRING_PROFILES_ACTIVE=internal
      - LOGGING_FILE=/axon-server-logs/axonserver-enterprise-1.log
      - AXONIQ_AXONSERVER_METRICS_GRPC_ENABLED=true
      - AXONIQ_AXONSERVER_METRICS_GRPC_PROMETHEUSENABLED=true
      - AXONIQ_AXONSERVER_METRICS_GRPC_JAEGERENABLED=true
      - AXONIQ_AXONSERVER_METRICS_GRPC_JAEGERENDPOINT=http://jaeger:14268/api/traces
      - AXONIQ_AXONSERVER_METRICS_GRPC_JAEGERSERVICENAME=axon-server-1
#      - AXONIQ_AXONSERVER_ACCESSCONTROL_ENABLED=true
#      - AXONIQ_AXONSERVER_ACCESSCONTROL_INTERNAL-TOKEN=itoken
    volumes:
      - axonserver-enterprise-1-log:/raft-log
      - axonserver-enterprise-1-eventstore:/eventstorage
      - axonserver-enterprise-1-controldb:/controldb
      - axonserver-logs:/axon-server-logs
      - axonserver-enterprise-1-security:/security
    ports:
      - '8024:8024'
      - '8124:8124'
  axonserver-enterprise-2:
    image: axonserver-enterprise
    hostname: axonserver-enterprise-2
    environment:
      - AXONIQ_AXONSERVER_EVENT_STORAGE=/eventstorage
      - AXONIQ_AXONSERVER_SNAPSHOT_STORAGE=/eventstorage
      - AXONIQ_AXONSERVER_CONTROLDB-PATH=/controldb
      - AXONIQ_AXONSERVER_NAME=axonserver-enterprise-2
      - AXONIQ_AXONSERVER_HOSTNAME=axonserver-enterprise-2
      - SERVER_PORT=8025
      - AXONIQ_AXONSERVER_PORT=8125
      - AXONIQ_AXONSERVER_REPLICATION_FLOW-BUFFER=50
      - AXONIQ_AXONSERVER_REPLICATION_MAX-SNAPSHOT-CHUNKS-PER-BATCH=10
      - AXONIQ_AXONSERVER_REPLICATION_MAX-ENTRIES-PER-BATCH=10
      - AXONIQ_AXONSERVER_REPLICATION_LOG-STORAGE-FOLDER=/raft-log
      - SPRING_PROFILES_ACTIVE=internal
      - LOGGING_FILE=/axon-server-logs/axonserver-enterprise-2.log
      - AXONIQ_AXONSERVER_METRICS_GRPC_ENABLED=true
      - AXONIQ_AXONSERVER_METRICS_GRPC_PROMETHEUSENABLED=true
      - AXONIQ_AXONSERVER_METRICS_GRPC_JAEGERENABLED=true
      - AXONIQ_AXONSERVER_METRICS_GRPC_JAEGERENDPOINT=http://jaeger:14268/api/traces
      - AXONIQ_AXONSERVER_METRICS_GRPC_JAEGERSERVICENAME=axon-server-2
#      - AXONIQ_AXONSERVER_ACCESSCONTROL_ENABLED=true
#      - AXONIQ_AXONSERVER_ACCESSCONTROL_INTERNAL-TOKEN=itoken
    volumes:
      - axonserver-enterprise-2-log:/raft-log
      - axonserver-enterprise-2-eventstore:/eventstorage
      - axonserver-enterprise-2-controldb:/controldb
      - axonserver-logs:/axon-server-logs
      - axonserver-enterprise-2-security:/security
    ports:
      - '8025:8025'
      - '8125:8125'
  axonserver-enterprise-3:
    image: axonserver-enterprise
    hostname: axonserver-enterprise-3
    environment:
      - AXONIQ_AXONSERVER_EVENT_STORAGE=/eventstorage
      - AXONIQ_AXONSERVER_SNAPSHOT_STORAGE=/eventstorage
      - AXONIQ_AXONSERVER_CONTROLDB-PATH=/controldb
      - AXONIQ_AXONSERVER_NAME=axonserver-enterprise-3
      - AXONIQ_AXONSERVER_HOSTNAME=axonserver-enterprise-3
      - SERVER_PORT=8026
      - AXONIQ_AXONSERVER_PORT=8126
      - AXONIQ_AXONSERVER_REPLICATION_FLOW-BUFFER=50
      - AXONIQ_AXONSERVER_REPLICATION_MAX-SNAPSHOT-CHUNKS-PER-BATCH=10
      - AXONIQ_AXONSERVER_REPLICATION_MAX-ENTRIES-PER-BATCH=10
      - AXONIQ_AXONSERVER_REPLICATION_LOG-STORAGE-FOLDER=/raft-log
      - SPRING_PROFILES_ACTIVE=internal
      - LOGGING_FILE=/axon-server-logs/axonserver-enterprise-3.log
      - AXONIQ_AXONSERVER_METRICS_GRPC_ENABLED=true
      - AXONIQ_AXONSERVER_METRICS_GRPC_PROMETHEUSENABLED=true
      - AXONIQ_AXONSERVER_METRICS_GRPC_JAEGERENABLED=true
      - AXONIQ_AXONSERVER_METRICS_GRPC_JAEGERENDPOINT=http://jaeger:14268/api/traces
      - AXONIQ_AXONSERVER_METRICS_GRPC_JAEGERSERVICENAME=axon-server-3
#      - AXONIQ_AXONSERVER_ACCESSCONTROL_ENABLED=true
#      - AXONIQ_AXONSERVER_ACCESSCONTROL_INTERNAL-TOKEN=itoken
    volumes:
      - axonserver-enterprise-3-log:/raft-log
      - axonserver-enterprise-3-eventstore:/eventstorage
      - axonserver-enterprise-3-controldb:/controldb
      - axonserver-logs:/axon-server-logs
      - axonserver-enterprise-3-security:/security
    ports:
      - '8026:8026'
      - '8126:8126'
  cli-configure-axonserver-cluster:
    build: ./axonserver-cli-image
    depends_on:
      - axonserver-enterprise-1
      - axonserver-enterprise-2
      - axonserver-enterprise-3
    command: ["./wait-for-it.sh axonserver-enterprise-1:8024 --strict --timeout=240 -- ./axonserver-cli.jar init-cluster -S http://axonserver-enterprise-1:8024 && ./wait-for-it.sh axonserver-enterprise-2:8025 --strict --timeout=90 -- ./axonserver-cli.jar register-node -S http://axonserver-enterprise-2:8025 -h axonserver-enterprise-1 -p 8224 && ./wait-for-it.sh axonserver-enterprise-3:8026 --strict --timeout=90 -- ./axonserver-cli.jar register-node -S http://axonserver-enterprise-3:8026 -h axonserver-enterprise-1 -p 8224"]

volumes:
  axonserver-enterprise-1-log:
  axonserver-enterprise-1-eventstore:
  axonserver-enterprise-1-controldb:
  axonserver-enterprise-2-log:
  axonserver-enterprise-2-eventstore:
  axonserver-enterprise-2-controldb:
  axonserver-enterprise-3-log:
  axonserver-enterprise-3-eventstore:
  axonserver-enterprise-3-controldb:
  axonserver-logs:
  axonserver-enterprise-1-security:
  axonserver-enterprise-2-security:
  axonserver-enterprise-3-security:
