spring:
  application:
    name: axondb-migration
  profiles:
    active: migrate-from-jpa
  jpa:
    database: default

axoniq:
  migration:
    batchSize: 100

  datasource:
    migration:
      url: jdbc:h2:./migrationdb

axon:
  serializer:
    events: xstream
