:doctype: book
:imagesdir: images
:numbered:

= AxonIQ AxonHub Guide
AxonIQ B.V.
:revnumber: 1.0
:revdate: {localdate}
:cliversion: 1.1
:Cli: axoniq-cli.jar
:CliCmd: java -jar {Cli}
:clientrevnumber: {revnumber}

== Introduction

=== About

AxonHub is a messaging platform specifically built to support distributed Axon Framework applications.
It is a drop in replacement for the other CommandBus, EventBus and QueryBus implementations.

The key characteristics for AxonHub are:

- Dedicated infrastructure for exchanging messages in a message-driven micro-services environment.
- Easy-to-use and easy-to-manage
- Built-in knowledge on CQRS message patterns

=== License

The Axon Framework itself is open source and licensed under the Apache License v2.0.

AxonIQ AxonHub is a commercial software product by AxonIQ B.V. Please contact us via https://axoniq.io or
sales@axoniq.io if you are interested in acquiring a license and support contract. To facilitate evaluation
and development, AxonIQ offers a free developers edition of the software.

The Java client to AxonHub is open source under the Apache License 2.0. It is available through
GitHub (https://github.com/AxonIQ) and can be downloaded from Maven Central.


== Architecture

=== Overview

In a message-driven micro-services environment it is extremely important that communication
between services is efficient, reliable and easy to manage and monitor. Routing of messages
should not require any manual configuration and adding new services should be easy to do.

With Axon Framework the internals of communication are hidden for the application developers.
AxonHub provides this same experience in a distributed environment. It is an easy-to-use,
easy-to-manage platform to handle all events, commands and queries.

AxonHub has knowledge about the different types of messages that are being exchanged:
events, sent from one service to one or many other services, to notify the services that something has happened,
commands, sent to one service to do something, potentially waiting for a result
queries, sent to one or more services to retrieve information.

Each of these messages requires a different strategy, all supported by AxonHub.

Applications connect to the messaging platform and register their capabilities. One application may be able to execute a specific set of commands, another may handle a number of queries. There may be multiple instances of the same application connected to the messaging platform, each instance having the same capabilities.

=== Message patterns

A client or application sends a request to the messaging platform. The platform finds the appropriate connected application(s) to send the request to, and forwards the request. It receives the reply, or replies, and forwards that to the caller.
Commands are always sent to exactly one application. Commands for the same aggregate are always sent to the same application instance, to avoid problems with concurrent updates of the aggregate.
Queries are sent to all applications capable of answering the query. If there are multiple instances of the same application, the query is only sent to one of the instances.
Events are stored in the event store and sent to all registered listeners.

=== High Available

AxonHub can operate in a clustered mode. Each node in the cluster is active and applications are dynamically load balanced over the nodes. Instances of the same application will connect to the same messaging node to optimize performance. Instances of different applications are distributed over the nodes to spread the load.


=== Flow control

AxonHub controls the flow of messages being sent to the message handlers. The message handlers sent a number of permits to the messing platform, indicating the number of messages the messaging platform may send. Once the handler is ready for more request it sends another message with a number of additional permits.
AxonHub queues messages when there are no permits for the handler left. When a handler is disconnected while there are still queued messages, these are re-routed to another handler (if possible).

=== QoS Messages

Clients can indicate priority of their request. This way, for example, commands originating from a batch process can be executed with lower priority than online request.

=== Access control

Applications need to be granted access to the messaging platform. This avoids the risk that random clients can start sending commands into the system.


=== Implementation technology

The AxonIQ AxonHub has been developed fully in Java, building on Spring Boot. It is distributed as a single jar
file containing all libraries used through shading.

Configuration information for AxonHub is stored in a small h2 database. This contains the information about the
messaging platform nodes and the applications that have access. This information is automatically replicated
between nodes in the cluster.

The messaging platform has 2 types of interfaces:

- HTTP
- gRPC (HTTP 2.0)

Communication between the standard Axon Framework AxonHub client and the messaging platform uses gRPC.

== Setting up the AxonHub server

=== Prerequisites
A Java 8+ JRE should be installed on the system.

=== Installation procedure

The AxonHub delivery contains the following artifacts:

- axonhub-server.jar
- axonhub.properties
- {Cli}
- AxonHub_Guide.pdf

Copy axonhub-server.jar and axonhub.properties to a directory of your choice.

To connect AxonHub to AxonDB fill in the address of the AxonDB servers in the property *axoniq.axondb.servers* in axonhub.properties.
The value of this property is a comma separated list of hostnames and optional gRPC port numbers of the AxonDB nodes, e.g.
```
axoniq.axondb.servers=server1,server2,server3
```
You can specify the port numbers when AxonDB is not running on the default port (8123), e.g.:
```
axoniq.axondb.servers=server1:9000,server2:9000,server3:9000
```


Default ports used by AxonHub are:

- 8024: HTTP port for REST calls and HTML pages
- 8124: gRPC port, used by applications to connect to AxonHub.
- 8224: Internal gRPC port, used by AxonHub nodes for internal communication

Basically, you are ready to go now. Start the AxonHub server using the following command:

[subs="attributes"]
```sh
# ./axonhub-server.jar
```
or when not running bash shell:
[subs="attributes"]
```sh
# java -jar axonhub-server.jar
```

To verify that the server is started correctly, open the page http://localhost:8024.


== Using AxonHub from applications

If you want to use AxonHub from an Axon application using Spring boot, you need to include the
axonhub-spring-boot-autoconfigure as a dependency in the project. This will set up the Axon EventBus,
CommandBus and QueryBus components to connect to AxonHub.

[subs="verbatim,attributes"]
```xml
<dependency>
  <groupId>io.axoniq</groupId>
  <artifactId>axonhub-spring-boot-autoconfigure</artifactId>
  <version>{clientrevnumber}</version>
</dependency>
```

Apart from this, all you need to do is define the following 3 properties in your application properties file:

```properties
axoniq.axonhub.servers=localhost
```
The servers property is a comma separated list of axonhub servers. Each server is described by its hostname
and optionally the gRPC port for the server. When AxonHub is running on the default ports, you can omit the port number,
otherwise add it like this:
```properties
axoniq.axonhub.servers=localhost:1234
```

The same configuration can also be done manually, when you are not using Spring boot. For this you need
to include the following dependency:

[subs="verbatim,attributes"]
```xml
<dependency>
  <groupId>io.axoniq</groupId>
  <artifactId>axonhub-client</artifactId>
  <version>{clientrevnumber}</version>
</dependency>
```

In your Axon application you need to configure the various buses manually, e.g.:

```java
public class AxonStarter {
    public static void main(String[] args) {
        AxonHubConfiguration axonhubConfiguration = AxonHubConfiguration.newBuilder("localhost", "AxonStarter").build();
        PlatformConnectionManager platformConnectionManager = new PlatformConnectionManager(axonhubConfiguration);

        Serializer serializer = new JacksonSerializer();
        EventBus axonHubEventStore = new AxonHubEventStore(axonhubConfiguration, platformConnectionManager, serializer);
        CommandBus localSegment = new SimpleCommandBus();
        CommandBus axonHubCommandBus = new AxonHubCommandBus(platformConnectionManager, axonhubConfiguration, localSegment, serializer,
                new AnnotationRoutingStrategy());

        QueryBus localQueryBus = new SimpleQueryBus();
        QueryBus axonHubQueryBus = new AxonHubQueryBus(platformConnectionManager, axonhubConfiguration, localQueryBus, serializer,
                new QueryPriorityCalculator() {});

        Configuration config = DefaultConfigurer.defaultConfiguration()
                .configureEventBus(c -> axonHubEventStore)
                .configureCommandBus(c -> axonHubCommandBus)
                .configureQueryBus(c -> axonHubQueryBus)
                // more configuration for Axon
                .configureSerializer(c -> serializer)
                .buildConfiguration();

        config.start();
    }
}
```

== Advanced configuration

=== Names and ports


- *axoniq.axonhub.name*: the unique node name of the AxonHub node is taken from the hostname of the server.
- *axoniq.axonhub.hostname*: the hostname of the AxonHub node, as returned to clients, is taken from the hostname of the server.
- *axoniq.axonhub.port*: the gRPC port for clients to connect is set to 8124 by default
- *server.port*: the HTTP port for REST clients to connect is set to 8024 by default

=== Database

By default each AxonHub node will create its own H2 database in a file axonhub-controldb in the working
directory. To change this, set the property:

- *axoniq.axonhub.controldb-path*: Path to controlDB

=== Logging

Logging is by default set to WARN level for all packages. To change the logging levels for
specific packages or classes add logging level properties to the axonhub.properties file, for example:
```
logging.level.io.axoniq.axonhub=INFO
```

Log messages are written to stdout by default. To change this add the properties logging.file and/or logging.path
to the axonhub.properties file.
```sh
# write log entries to file called messaging.log
logging.file=messaging.log
# create logfiles in directory /var/log
logging.path=/var/log
```

=== Cluster [Not in Development edition]

When runnning AxonHub in a licensed edition, you can set up a cluster of AxonHub servers. The servers run in
active/active mode, so each node can receive and handle requests.

You can set the following properties in the axonhub.properties configuration file:

- *axoniq.axonhub.name* - logical name of the node in the cluster. _This must be unique within the cluster_.
- *axoniq.axonhub.hostname* - sets the hostname as this node advertises it to clients
- *axoniq.axonhub.domain* - sets the domain as used in returning the server address to clients
- *axoniq.axonhub.internal-hostname* - hostname to be used by other nodes in the server cluster
- *axoniq.axonhub.internal-domain* - domain to be used by other nodes in the server cluster
- *axoniq.axonhub.internal-port* - internal gRPC port number for communication to other nodes

When there is no hostname specified it defaults to the hostname as returned by the *hostname* command.


Sample configuration:
----
axoniq.axonhub.hostname=messaging1.axoniq.io
axoniq.axonhub.name=messaging1
----

Connecting the nodes of a cluster is done using the command line interface.
Send the register-node command to one node, specifying the address of another node
in the cluster, e.g.

[subs="attributes"]
```sh
# {CliCmd} register-node -S http://node-to-add:port -h node-in-cluster -p internal-port-of-node-in-cluster
```

This only has to be done once, each node maintains a list of all nodes in the cluster.


=== Flow control

Flow control is the process of managing the rate of data transmission between two nodes
to prevent a fast sender from overwhelming a slow receiver.

In the messaging platform flow control is possible both between the messaging platform and the message handlers,
and between the nodes in the messaging platform cluster.

Messaging platform - message handler::

The client needs to set the following properties to configure flow control:

* *axoniq.axonhub.initial-nr-of-permits* [100000] - number of messages that the server can initially send to client.
* *axoniq.axonhub.nr-of-new-permits* [90000] - additional number of messages that the server can send to client.
* *axoniq.axonhub.new-permits-threshold* [10000] -  when client reaches this threshold in remaining messages, it sends a request with additional number of messages to receive.

Message platform nodes::

Set the following properties to set flow control on the synchronization between master and replicas:

* *axoniq.axonhub.commandFlowControl.initial-nr-of-permits* [100000] - number of messages that the master can initially send to replica.
* *axoniq.axonhub.commandFlowControl.nr-of-new-permits* [90000] - additional number of messages that the master can send to replica.
* *axoniq.axonhub.commandFlowControl.new-permits-threshold* [10000] - when replica reaches this threshold in remaining messages, it sends a request with additional number of messages to receive.
* *axoniq.axonhub.queryFlowControl.initial-nr-of-permits* [100000] - number of messages that the master can initially send to replica.
* *axoniq.axonhub.queryFlowControl.nr-of-new-permits* [90000] - additional number of messages that the master can send to replica.
* *axoniq.axonhub.queryFlowControl.new-permits-threshold* [10000] - when replica reaches this threshold in remaining messages, it sends a request with additional number of messages to receive.


=== Access control

To enable access control add the following property to the axonhub.properties:

* *axoniq.axonhub.accesscontrol.enabled*=true

To register an application and get an access token use the following command:

[subs="attributes"]
```
{CliCmd} register-application -S http://messaging:8080 -a applicationname -d description -r READ,WRITE
```

The address of the server specified in this command is the address of the current master node. The master will distribute the applications to all the replicas.

This command returns the generated token to use. _Note that this token is only generated once, if you loose it you must delete the application and register it again to get a new token_.
Specify the access token in the client by setting the property:

* *axoniq.axonhub.token*=[Token]

In the Developer Edition it is not possible to create applications. If you want to test access control in this edition
specify the property *axoniq.axonhub.accesscontrol.token* with any value you want on the AxonHub server and set the same value
in the *axoniq.axonhub.token* property on the client.

You can access the AxonHub webpages when access control is enabled by providing a username and password. Users are created
through the command line using the following command:

[subs="attributes"]
```
{CliCmd} register-user -S http://axonhub:8024 -u USERNAME
```

The command will prompt for a password.

Note that the command line interface also requires a token when executing remote commands. If you execute a command
from an AxonHub node itself, you do not need to provide a token.

Access control can also be enabled on the AxonDB server. In this case the messaing platform
nodes must provide a token with their requests to AxonDB. This token must be
specified in the property *axoniq.axondb.token* in the messaging platform node configuration.

If access control is enabled and the messaging platform is running in clustered mode,
the nodes in the cluster also need to attach a token with the messages sent between them.
This token must be defined in the application properties file on each node with property *axoniq.axonhub.accesscontrol.internal-token*. The value of this property
must be the same for all nodes.


=== SSL

Requires private key and public certificate. The same certificate is used to connect to all event store servers.

For gRPC communication add file locations to the axonhub.properties file:

* *axoniq.axonhub.ssl.cert-chain-file* - location of the public certificate file
* *axoniq.axonhub.ssl.private-key-file* - location of the private key file

Sample:
----
axoniq.axonhub.ssl.enabled=true
axoniq.axonhub.ssl.cert-chain-file=./resources/axoniq-public.crt
axoniq.axonhub.ssl.private-key-file=./resources/axoniq-private.pem
----

For HTTPs configuration the certificate and key need to be installed in a p12 keystore.
To install the keys use the following command:
```
openssl pkcs12 -export -in [public-cert-file] -inkey [private-key-file] -out [keystore-file] -name [alias]
```

Configure the Messaging Platform server to use HTTPs by adding the following properties to the axonhub.properties file:
----
server.port=8443
server.ssl.key-store=[keystore-file]
server.ssl.key-store-password=[password]
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=[alias]
----

=== Keep-Alive (since 1.0.3)

All components in the AxonHub environment can exchange keep alive signals to ensure that the network connections are still available.
Keep-alive checks are available between:

- AxonHub nodes in a cluster
- AxonHub nodes and AxonDB nodes
- Connected applications and AxonHub nodes

Keep-alive between the AxonHub nodes is enabled by default.

Keep-alive checks with AxonDB require AxonDB version 1.2.3 or higher.
To enable keep-alive between AxonHub and AxonDB set the following properties in the axonhub.properties file:

----
# frequency to send keep-alive messages in ms.
axoniq.axondb.keep-alive-time=2000
# timeout for keep-alive messages in ms.
axoniq.axondb.keep-alive-timeout=2000
----

Keep-alive checks with connected applications require AxonHub client version 1.0.3 or higher.
To enable keep-alive between connected applications and AxonHub set the following properties in the application.properties file:

----
# frequency to send keep-alive messages in ms.
axoniq.axonhub.keep-alive-time=2000
# timeout for keep-alive messages in ms.
axoniq.axonhub.keep-alive-timeout=2000
----

== Operations

=== Starting the AxonHub
Start AxonHub with the following queryDefinition:
[subs="attributes"]
```sh
# java -jar axonhub-server.jar.jar
```

=== Stopping the Event Store
Either press Ctrl-C in the console window, or kill the process.

[appendix]

include::../resources/releasenotes.adoc[]

[appendix]
== Configuration Properties

The following table gives a complete list of all the configuration properties available for the AxonHub Server.

[width="95%", cols="3,1,1,5", options="header"]
|===========================
|Name|Default value|Type|Description
|server.port|8024|Integer|The Http Server port
|axoniq.axonhub.name||String|Node name of this axonhub platform node, if not set defaults to the hostname.
|axoniq.axonhub.port|8124|Integer|gRPC port for axonhub platform
|axoniq.axonhub.internal-port|8224|Integer|gRPC port for communication between messing platform nodes
|axoniq.axonhub.hostname||String|Hostname of this node as communicated to clients, defaults to the result of hostname command
|axoniq.axonhub.internal-hostname||String|Hostname as communicated to other nodes of the cluster. Defaults to hostname.
|axoniq.axonhub.domain||String|Domain of this node as communicated to clients. Optional, if set will be appended to the hostname in communication with clients.
|axoniq.axonhub.internal-domain||String|Domain as communicated to other nodes of the cluster. Optional, if not set, it will use the domain value.
|axoniq.axonhub.keep-alive-time|2500|Long|Interval for keep alive messages between AxonHub nodes, 0 disables keep alive messages
|axoniq.axonhub.keep-alive-timeout|5000|Long|Timeout for keep alive messages, only of keep-alive-time is greater than 0
|axoniq.axonhub.min-keep-alive-time|1000|Long|Minimium keep alive time allowed for clients
|axoniq.axondb.servers||String|Comma-separated list of AxonDB servers
|axoniq.axondb.token||String|Token to add to AxonDB requests
|axoniq.axondb.ssl-enabled|false|Boolean|SSL enabled for connection to AxonDB
|axoniq.axondb.cert-file||String|Certificate used for connection to AxonDB
|axoniq.axondb.keep-alive-time|0|Long|Interval for keep alive messages to AxonDB, 0 disables keep alive messages
|axoniq.axondb.keep-alive-timeout|5000|Long|Timeout for keep alive messages to AxonDB, only of keep-alive-time is greater than 0
|axoniq.axonhub.accesscontrol.enabled|false|Boolean|Access control active
|axoniq.axonhub.accesscontrol.cache-ttl|30000|Long|Milliseconds that authenticated tokens will be cached
|axoniq.axonhub.accesscontrol.internal-token||String|Token to add to AxonHub internal cluster message
|axoniq.axonhub.accesscontrol.token||String|Token expected from client requests [Developer edition only]
|axoniq.axonhub.cluster.enabled|false|Boolean|Cluster enabled
|axoniq.axonhub.cluster.connection-check-delay|1000|Long|Delay before the first run of the connection checker (in ms.)
|axoniq.axonhub.cluster.connection-check-interval|1000|Long|Interval between each run of the connection checker (in ms.)
|axoniq.axonhub.cluster.rebalance-delay|7|Long|Delay before the first run of the rebalancer (in seconds) [Enterprise edition only]
|axoniq.axonhub.cluster.rebalance-interval|15|Long|Interval between each run of the rebalancer (in seconds) [Enterprise edition only]
|axoniq.axonhub.command-flow-control.initial-permits|10000|Long|Initial number of permits granted in communication between AxonHub nodes.
|axoniq.axonhub.command-flow-control.new-permits|10000|Long|Additional number of permits granted in communication between AxonHub nodes.
|axoniq.axonhub.command-flow-control.threshold|1000|Long|Threshold at which the node will send another grant of newPermits to the connected platform node.
|axoniq.axonhub.query-flow-control.initial-permits|10000|Long|Initial number of permits granted in communication between AxonHub nodes.
|axoniq.axonhub.query-flow-control.new-permits|10000|Long|Additional number of permits granted in communication between AxonHub nodes.
|axoniq.axonhub.query-flow-control.threshold|1000|Long|Threshold at which the node will send another grant of newPermits to the connected platform node.
|axoniq.axonhub.ssl.enabled|false|Boolean|SSL enabled for gRPC servers
|axoniq.axonhub.ssl.cert-chain-file||String|
|axoniq.axonhub.ssl.internal-cert-chain-file||String|
|axoniq.axonhub.ssl.private-key-file||String|
|axoniq.axonhub.controldb-path|.|String|Path to the AxonHub controlDB|
|===========================

[appendix]
== Client Configuration Properties

The following table gives a complete list of all the configuration properties available for
 the AxonHub Client.
[width="95%", cols="3,1,1,5", options="header"]
|===========================
|Name|Default value|Type|Description
|axoniq.axonhub.servers||String|Comma separated list of AxonHub servers
|axoniq.axonhub.ssl-enabled|false|Boolean|Use SSL for connection to AxonHub
|axoniq.axonhub.cert-file||String|Path to certificate file to use for SSL
|axoniq.axonhub.token||String|Authentication token sent with each request. Only if AxonHub is running in Authentication mode.
|axoniq.axonhub.client-name||String|Client name as communicated to AxonHub. If not set, defaults to hostname:processId.
|axoniq.axonhub.component-name||String|Component name, all instances of the same application must have the same component name. Defaults to Spring application name.
|axoniq.axonhub.initial-nr-of-permits|100000|Long|Initial number of permits granted in communication with AxonHub.
|axoniq.axonhub.new-permits-threshold|1000|Long|Threshold at which the node client send another grant of newPermits to the connected platform node.
|axoniq.axonhub.nr-of-new-permits|90000|Long|Additional number of permits granted in communication with AxonHub nodes.
|axoniq.axonhub.command-threads|10|Integer|Number of threads processing commands
|axoniq.axonhub.query-threads|10|Integer|Number of threads processing queries
|axoniq.axonhub.context||String|AxonHub context used by the application (Enterprise Edition only)
|axoniq.axonhub.keep-alive-time|0|Long|Interval for keep alive messages, 0 disables keep alive messages
|axoniq.axonhub.keep-alive-timeout|5000|Long|Timeout for keep alive messages, only of keep-alive-time is greater than 0
|===========================
