create table LOAD_BALANCING_STRATEGY
( ID bigint generated by default as identity,
	NAME VARCHAR(255) not null,
	LABEL VARCHAR(255) not null,
	FACTORY_BEAN VARCHAR(255) not null,
	primary key (ID)
);

create unique index UK_LOAD_BALANCING_STRATEGY_NAME on LOAD_BALANCING_STRATEGY (NAME);

INSERT INTO LOAD_BALANCING_STRATEGY (FACTORY_BEAN, LABEL, NAME)
VALUES ('NoLoadBalance', 'Default (disabled)', 'default');
INSERT INTO LOAD_BALANCING_STRATEGY (FACTORY_BEAN, LABEL, NAME)
VALUES ('ThreadNumberBalancingStrategy', 'Thread Number', 'threadNumber');

create table PROCESSOR_LOAD_BALANCING
(
	COMPONENT VARCHAR(255) not null,
	CONTEXT VARCHAR(255) not null,
	NAME VARCHAR(255) not null,
	STRATEGY VARCHAR(255) not null,
	primary key (COMPONENT, CONTEXT, NAME)
)
;



