create table context (id bigint generated by default as identity, context varchar(255) not null, primary key (id));

create table context_cluster_node (
  context_id bigint not null REFERENCES context(id),
  cluster_node_name varchar(255) not null REFERENCES cluster_node(name),
  PRIMARY KEY (context_id, cluster_node_name)
);

insert into context( context) values ('default');