server:
  port: 8024

spring:
  application:
    name: AxonServerEnterprise

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false

  datasource:
    url: jdbc:h2:nio:${axoniq.axonserver.controldb-path:.}/axonserver-controldb

  h2:
    console:
      enabled: true
      path: /h2-console

axoniq:
  axonserver:
    port: 8124
    internal-port: 8224
    accesscontrol:
      enabled: false
    ssl:
      enabled: false
    cluster:
      enbaled: true
    metrics-interval: 15
    metrics-synchronization-rate: 2500
    connect2contexts: node-contexts

logging:
  level:
    root: WARN
    io.axoniq.axonserver.AxonServerEnterprise: INFO
    io.axoniq.axonserver.grpc.Gateway: INFO
    io.axoniq.axonserver.enterprise.cluster.internal.MessagingClusterServer: INFO
    org.springframework.boot.web.embedded.tomcat.TomcatWebServer: INFO
    org.hibernate.orm.deprecation: ERROR


management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: metrics,info,health,loggers


info:
  app:
    name: ${spring.application.name}
    description: AxonIQ
    version: @project.version@