server:
  port: 8024

spring:
  application:
    name: AxonServer Enterprise

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false

  datasource:
    url: jdbc:h2:retry:${axoniq.axonserver.controldb-path:./data}/axonserver-controldb
    hikari:
      connection-init-sql: select 1;
      leak-detection-threshold: 2000

  transaction:
    default-timeout: 3000

  h2:
    console:
      enabled: true
      path: /h2-console

axoniq:
  axonserver:
    metrics-synchronization-rate: 2500

logging:
  level:
    root: WARN
    io.axoniq.axonserver.AxonServerEnterprise: INFO
    io.axoniq.axonserver.grpc.Gateway: INFO
    io.axoniq.axonserver.enterprise.cluster.internal.MessagingClusterServer: INFO
    io.axoniq.axonserver.enterprise.logging: INFO
    io.axoniq.axonserver.logging: INFO
    io.axoniq.axonserver.cluster: INFO
    org.springframework.boot.web.embedded.tomcat.TomcatWebServer: INFO
    org.springframework.http.converter.json.Jackson2ObjectMapperBuilder: ERROR
    org.hibernate.orm.deprecation: ERROR
    com.zaxxer.hikari: ERROR
    io.grpc.netty.NettyServerHandler: ERROR

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: metrics,info,health,loggers,prometheus,env
  endpoint:
    health:
      show-details: always

info:
  app:
    name: ${spring.application.name}
    description: AxonIQ
    version: @project.version@